var data = {
	vocabulary: [
		[1,	"contempt", 		"Verachtung"],
		[1,	"compassion", 		"Barmherzigkeit"],
		[1, "futility", 		"Nutzlosigkeit"],
		[1, "futility", 		"Sinnlosigkeit"],
		[1, "snarly", 			"verwirrend"],
		[1, "dismay", 			"Bestürzung"],
		[1, "dismay", 			"Entsetzen"],
		[1, "eerie", 			"unheimlich"],
		[1, "eerie", 			"furchterregend"],
		[1, "squalid", 			"dreckig"],
		[1, "squalid", 			"schmutzig"],
		[1, "squalid", 			"verwahrlost"],
		[1, "perilous", 		"gefährlich"],
		[1, "to obliterate", 	"auslöschen"],
		[1, "to obliterate", 	"vernichten"],
		[1, "resentment", 		"Ärger"],
		[1, "resentment", 		"Groll"],
		[1, "contradiction",	"Widerspruch"],
		[1, "contradiction",	"Ungereimtheit"],
		[1, "decrepit",			"altersschwach"],
		[1, "to cherish",		"aufrechterhalten"],
		[1, "to cherish",		"hegen"],
		[1, "to cherish",		"aufziehen"],
		[1, "to cherish",		"wertschätzen"],
		[2, "benign",			"gutartig"],
		[2, "benign",			"freundlich"],
		[2, "benign",			"harmlos"],
		[2, "fierce",			"wild"],
		[2, "imperious",		"herrisch"],
		[2, "imperious",		"gebieterisch"],
		[2, "lassitude",		"Erschöpfung"],
		[2, "prone",			"auf dem Bauch liegend"],
		[2, "swiftly",			"schnell"],
		[2, "swiftly",			"geschwind"],
		[2, "to burgeon", 		"knospen"],
		[2, "to beckon",		"jmd. winken"],
		[2, "sentient", 		"empfindungsfähig"],
		[2, "sentient",			"empfindend"],
		[2, "to perch", 		"sich niederlassen"],
		[2, "to perch", 		"sich setzen"],
		[2, "fraught", 			"belastet"],
		[2, "fraught", 			"nervenaufreibend"],
		[2, "fraught", 			"angespannt"],
		[2, "fraud", 			"Betrug"],
		[2, "gingerly",			"behutsam"],
		[2, "distinction", 		"Unterschied"],
		[2, "distinction", 		"Andersartigkeit"],
		[2, "distinction", 		"Auszeichnung"],
		[2, "commuter train", 	"Pendlerzug"],
		[3, "cairn", 			"Steinhaufen"],
		[3, "magpies",			"Elstern"],
		[3, "raucous", 			"johlend"],
		[3, "raucous", 			"heiser"],
		[3, "raucous", 			"lärmend"],
		[3, "tiding",			"(kurze) Nachricht"],
		[3, "jumbled", 			"durcheinandergewürfelt"],
		[3, "bank", 			"Ufer"],
		[3, "bank", 			"Böschung"],
		[3, "scrap", 			"Bruchstück"],
		[3, "scrap", 			"Schrott"],
		[3, "tangy",			"scharf (Geschmack)"],
		[3, "tangy", 			"kräftig (Geschmack)"],
		[3, "makeshift",		"behelfsmäßig"],
		[3, "whip",				"rennen (ugs.)"],
		[3, "whip",				"flitzen (ugs.)"],
		[3, "whip",				"rasen (ugs.)"],
		[3, "utterly",			"absolut"],
		[3, "utterly",			"ganz und gar"],
		[3, "wretched",			"miserabel"],
		[3, "wretched",			"verachtenswert"],
		[3, "wretched",			"unglücklich"],
		[3, "oblivious",		"vergesslich"],
		[3, "dread",			"große Furcht"],
		[3, "dread",			"Heidenangst"]
	]
};